spring.application.name=integrador-estoque

# --- ESSENCIAL PARA AS TABELAS NÃO SUMIREM ---
# Garante que o Hibernate não dê DROP nas tabelas manuais de Produto e Estoque
spring.jpa.hibernate.ddl-auto=none

# --- PERFORMANCE E DIALETO ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.fetch_size=100

# --- MENSAGERIA (RABBITMQ) ---
spring.amqp.deserialization.trust.all=true

# --- LOGS DE DEBUG (Úteis) ---
spring.jpa.show-sql=true
# logging.level.org.hibernate.orm.jdbc.bind=TRACE (Habilite apenas se precisar ver o XML no console)