CREATE TABLE PRODUTO (
    ID_PROD INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- chave primaria 
    PRODUTO VARCHAR2(300),
    LOCAL_ESTOQUE VARCHAR2(300),
    UF_CIDADE VARCHAR2(2),
    CIDADE_ESTOQUE VARCHAR2(30))


CREATE TABLE ESTOQUE (
    ID_PROD INT PRIMARY KEY,
    QTD_ATUAL NUMBER(7),
    DATA_ULTIMA_VENDA TIMESTAMP,
    CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PROD INT,
    NOME_PRODUTO VARCHAR2(300),
    QUANTIDADE NUMBER(7),
    VENDEDOR VARCHAR2(50),
    CLIENTE VARCHAR2(50),
    DATA_PEDIDO TIMESTAMP DEFAULT SYSTIMESTAMP,
    VALOR_TOTAL NUMBER(10, 2),
    CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD)
);
ALTER TABLE PEDIDO ADD XML_INTEGRACAO CLOB;

senha _ homologacao: 8958316181009917